import { useLocation, useNavigate, Navigate } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import { ArrowLeft, Share2 } from 'lucide-react'
import Header from '../components/Header'

export default function ResultPage() {
  const location = useLocation()
  const navigate = useNavigate()
  const data = location.state as { final_plan: string } | null

  if (!data || !data.final_plan) {
    // If user navigates here directly without data, send them back to plan
    return <Navigate to="/plan" replace />
  }

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: 'My Travel Guide',
        text: 'Check out this awesome travel itinerary generated by Wanderful!',
        url: window.location.href,
      }).catch(console.error)
    } else {
      alert('Sharing not supported on this browser.')
    }
  }

  return (
    <div className="min-h-screen flex flex-col bg-[#0a0a0a] text-white relative" style={{ fontFamily: "'Inter', sans-serif" }}>
      <Header />
      
      <main className="flex-1 max-w-4xl w-full mx-auto p-6 md:p-12 relative z-10 pt-8 pb-20">
        
        <div className="flex items-center justify-between mb-10">
          <button 
            onClick={() => navigate('/plan')}
            className="flex items-center gap-2 text-white/50 hover:text-white transition-colors text-sm font-medium"
          >
            <ArrowLeft className="w-4 h-4" />
            Plan Another Trip
          </button>
          
          <button
            onClick={handleShare}
            className="flex items-center gap-2 bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-full px-4 py-2 transition-all text-sm font-medium"
          >
            <Share2 className="w-4 h-4" />
            Share
          </button>
        </div>

        <div className="bg-[#111] border border-white/10 rounded-3xl p-8 md:p-12 shadow-2xl relative overflow-hidden">
          
          {/* Decorative background glow */}
          <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-white/5 blur-[150px] rounded-full pointer-events-none" />

          {/* Markdown Content styling */}
          <article className="prose prose-invert max-w-none prose-headings:font-medium prose-h1:text-3xl prose-h2:text-2xl prose-h3:text-xl prose-a:text-blue-400 prose-li:text-white/80 prose-p:text-white/80 prose-p:leading-relaxed prose-strong:text-white relative z-10">
            <ReactMarkdown>{data.final_plan}</ReactMarkdown>
          </article>

        </div>
      </main>
    </div>
  )
}
